[package]
name = "dicom_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.8.0"
dicom = "0.8.1"
anyhow = "1.0"
smallvec = "1.14.0"
dicom-pixeldata = { version = "0.8", features = ["image"] }